name: doctor_reservation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ğŸ Cupertino icons for iOS-style widgets
  cupertino_icons: ^1.0.8

  # ğŸ“¦ State management
  flutter_bloc: ^8.1.5

  # â„ï¸ Code generator (mainly used with cubit & retrofit)
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0

  # ğŸ’‰ Dependency injection
  get_it: ^7.7.0

  # ğŸ”„ JSON serialization (model generation)
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

  # ğŸŒ Networking
  dio: ^5.4.2
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.2

  # ğŸŒ Localization
  intl: ^0.19.1
  easy_localization: ^3.0.4

  # ğŸ’¦ Splash screen configuration
  flutter_native_splash: ^2.4.0

  # ğŸ–¼ï¸ SVG support
  flutter_svg: ^2.1.0

  # ğŸ“± Responsive design (screen adaptation)
  flutter_screenutil: ^5.9.2

  # ğŸ”¥ Firebase core
  firebase_core: ^2.28.0

  # ğŸ–¼ï¸ Image caching
  cached_network_image: ^3.3.2

  # ğŸ” Secure storage
  shared_preferences: ^2.2.4
  flutter_secure_storage: ^9.2.3

  # âœ¨ Shimmer loading effect
  shimmer: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # âœ… Lint rules and code style checks
  flutter_lints: ^5.0.0

  # ğŸ”¨ Code generation tool
  build_runner: ^2.4.9
